@baseUrl = http://localhost:3000
@userId = 9
@teamId = 1
@companyId = 1

### Login as Admin
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "alice.admin@acme.com",
  "password": "ChangeMe123!"
}

###

@token = {{login.response.body.accessToken}}

### Get current user
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}

### Create user
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John",
  "surname": "Doe",
  "email": "john.doe@example.com",
  "password": "P@ssw0rd!",
  "phone": "+11234567890",
  "role": "EMPLOYEE"
}

### Get all users
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Get user by id
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}}

### Update user
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Johnny B. Goodee",
  "phone": "+11987654321"
}

### Delete user
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}}

### Create company
POST {{baseUrl}}/companies
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Acme Corp",
  "domain": "acme.com"
}

### Get all companies
GET {{baseUrl}}/companies
Authorization: Bearer {{token}}

### Get company by id
GET {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}

### Update company
PATCH {{baseUrl}}/companies/{{companyId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Acme Corporation",
  "domain": "acme.example"
}

### Delete company
DELETE {{baseUrl}}/companies/{{companyId}}
Authorization: Bearer {{token}}

### Create team
POST {{baseUrl}}/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Engineering",
  "companyId": {{companyId}}
}

### Get all teams
GET {{baseUrl}}/teams
Authorization: Bearer {{token}}

### Get team by id
GET {{baseUrl}}/teams/{{teamId}}
Authorization: Bearer {{token}}

### Update team
PATCH {{baseUrl}}/teams/{{teamId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Product Engineering",
  "companyId": {{companyId}}
}

### Delete team
DELETE {{baseUrl}}/teams/{{teamId}}
Authorization: Bearer {{token}}
